### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by notDavid** [tyirvine/Duplicate-Tab#3]
Hi there, thanks for the extension :)

Please consider implementing a keyboard shortcut to trigger it.

Thank you!

**Comment by notDavid** [comment]
@tyirvine Hi @tyirvine, just curious… any luck submitting to the AppStore yet? 😊

**Comment by tyirvine** [comment]
@notDavid I will soon! I'm just having a new icon designed as the old one was similar to some other apps. Once it is finished I will upload it.

I was able to build it though and it looks great! It works good for both iPad and iOS. I had to change the permissions though to always active instead active when pressed, but I don't think anyone will really mind.

![image](https://user-images.githubusercontent.com/39813066/141001262-367abb61-b5cc-4116-9ec0-04cee2420ff8.png)

**Comment by notDavid** [comment]
Okay i see. Looks good, looking forward to it.

**Comment by tyirvine** [comment]
@notDavid Hey! Sorry for the long wait. The update is up!

Thank you for your patience! Enjoy!

If you have any issues let me know.

**Comment by notDavid** [comment]
Hey @tyirvine, great thanks!

The default shortcut didn't work for me, because this seems to already be bound to "Show the dock" in iPadOS. So i think it can't be 'overruled'?

After changing that to `option + shift + D` it's working great though 👌🏼

**Comment by tyirvine** [comment]
@notDavid oh shoot! I'm so sorry. I tested it on an iPad simulator but I guess it didn't show that problem. I apologize. I'll update it now.

**Comment by notDavid** [comment]
No worries! it was very easy to change.

But for new users you'd want to have a working default setting of course...

**Comment by tyirvine** [comment]
@notDavid I'm going to change the default shortcut to `option + D`, I don't think it's causing any issues. Do you think that would be okay for others with an iPad?

**Comment by notDavid** [comment]
Sounds like a good idea, i just tested and `option+d` is working 👍🏼

**Comment by tyirvine** [comment]
@notDavid Okay, I noticed `option+d` still inputs a glyph into a text box when used so I think I'm going to go with `ctrl+d` and then everyone can pick something else if they want.

Thank you for alerting me of this so quickly! Hopefully, I'll be able to fix this before a lot of people update!

**Comment by notDavid** [comment]
Good catch.

However `Ctrl+d` is not working for me.. it doesn't do anything.

Also i now see `Option+Shift+d` gives me `Î` in a textbox.

**Comment by tyirvine** [comment]
@notDavid oh no lol... I got some bad documentation or I misread something!!!

It turns out the JavaScript was not reading the control modifier at all! I was reading Mozilla accepted MacCtrl as the key code for Apple devices, but that must be strictly for Macs or something else entirely!

I submitted the update and everything was working fine once I made that change.

Thank you so much! Dodged a bullet there lol! The default shortcut is now `ctrl + d`. The update should be made available tonight or tomorrow morning. Again, thank you so much for your patience!

<img width="277" alt="Screen Shot 2021-12-02 at 5 53 58 PM" src="https://user-images.githubusercontent.com/39813066/144516097-16efac79-96f6-4bc2-a369-ea979d04a6a2.png">
!!

**Comment by notDavid** [comment]
Well, you'd probably be the first person in the world to release something without a single bug 😄

I'll let you know in case i run into anything else when i see the update tomorrow ✌🏼

**Comment by notDavid** [comment]
> The update should be made available tonight or tomorrow morning.

fyi: not seeing an update yet.

**Comment by tyirvine** [comment]
@notDavid sorry, it seems App Store review team is busy. Usually they review it pretty quickly but it's still waiting for review. :(

**Comment by notDavid** [comment]
Just tested and it's working fine 👌🏼

Thank you! 👍🏼

**Comment by notDavid** [comment]
Hey @tyirvine, fyi: i just found out `Ctrl+d` is the shortcut for **forward delete**.

So, when the cursor is in a text field before another character, it deletes the character in front just before duplicating the tab 😊

**Comment by tyirvine** [comment]
@notDavid I usually don’t mess up this bad lol. I’ll submit an update tomorrow! Sorry. Thank you for the help!

**Comment by notDavid** [comment]
@tyirvine no worries, it's a minor and the shortcut can easily be changed by the user 👌🏼

**Comment by tyirvine** [comment]
@notDavid hey the update is up! I apologize, I forgot to tell you. I posted about the app on Reddit and someone said they couldn't get the shortcut to work. Are you having any troubles?

I tested it on an iPhone with an external keyboard and it seems totally fine.

**Comment by notDavid** [comment]
Hey @tyirvine, i just tested the new version on the iPad and it seems to be working fine here too... 👍🏼

PS. I wonder what would happen if another extension would assign the same shortcut... also i noticed it doesn't work when a .pdf is open in Safari (the url is a pdf.)

**Comment by tyirvine** [comment]
@notDavid Awesome! I also tested it on a wiped iPad simulator just to be sure and it worked just fine there as well. Thank you for letting me know!

To your p.s. - shortcuts aren't officially supported by Safari on iOS so it'd be likely that both extensions would activate as there's no communication between them.

PDFs I suppose would just be a file the browser has loaded and therefore maybe the content script, which listens for shortcut presses, wouldn't get added? It should still work however by tapping the extension.

Merry Christmas! Happy holidays! 🎄
